### ISSUE TITLE
java2jsonld serialization is too verbose for java properties without values

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/jb4jsonld#2]
Java objects with empty properties (i.e. empty collections or null values for simple java fields) are serialized to jsonld by empty array [] and empty objects {}. This is unnecessary and makes jsonld file hard to read in case where there are many empty properties.

An example of an annotated class and respective jsonld file is in attachment. The redundant part of jsonld is:
        **"form:has-preceding-question": [],
        "form:has-question-origin": {}**     
It would be sufficient to exclude serialization of properties **form:has-preceding-question**, **form:has-question-origin** from the final output.

  
[serialized-excerpt.jsonld.txt](https://github.com/kbss-cvut/jb4jsonld/files/1691743/serialized-excerpt.jsonld.txt)
[Question.java.txt](https://github.com/kbss-cvut/jb4jsonld/files/1691747/Question.java.txt)

**Comment by ledsoft** [comment]
The array (`has-preceding-question`) seems to be the result of the field being initialized to an empty set (judging by the attached class declaration).

The empty object (`has-question-origin`) is because of the lack of support for plain identifier object property values. I opened an issue for it - #4 .

**Comment by ledsoft** [comment]
Closing the issue.
