### ISSUE TITLE
AssertionErrors from valid JSON-LD input

### ISSUE THREAD

**Issue by TGNThump** [kbss-cvut/jb4jsonld#22]
A number of valid activitystreams/jsonld tests in [ActivityStreams4J](https://github.com/TGNThump/ActivityStreams4J) error with AssertionErrors from JB4JSONLD in a variety of places:

- cz.cvut.kbss.jsonld.deserialization.expanded.Deserializer.getObjectTypes(Deserializer.java:54)
- cz.cvut.kbss.jsonld.deserialization.DefaultInstanceBuilder.openObjectForProperty(DefaultInstanceBuilder.java:71)
- cz.cvut.kbss.jsonld.deserialization.expanded.ExpandedJsonLdDeserializer.deserialize(ExpandedJsonLdDeserializer.java:42)

I can provide specific examples of inputs if necessary, but it might be easier for you to clone ActivityStreams4J and run the tests yourself to be able to debug them, or look at the [assertion errors from a recent build](https://github.com/TGNThump/ActivityStreams4J/actions/runs/135288610) (please ignore the tests that fail with errors other than java.lang.AssertionError).

**Comment by ledsoft** [comment]
Some of the issues have been fixed in 0.6.0. There remain stuff I'd like to look into, mainly the ability to deserialize objects when the target field type is `Object`.
There are, however, several issue with the input/mapping. For example, some tests attempt to deserialize a zoned datetime into an object property field, which is incorrect.
I'll keep the issue open as there are things that need to be fixed on our side. Feel free to provide additional feedback.

**Comment by TGNThump** [comment]
Thanks for the update and bugfixes, I'll switch to using 0.6.0 and look into the mapping issues.

**Comment by ledsoft** [comment]
Hi, you can try using 0.7.0, there are further fixes.

**Comment by TGNThump** [comment]
Thank you very much.
I think that's all the bugs covered under the scope of this issue fixed, so I'll close this issue. Feel free to re-open if I'm wrong.
