### ISSUE TITLE
Classpath scanning does not work for Spring Boot-based JARs

### ISSUE THREAD

**Issue by ledsoft** [kbss-cvut/jb4jsonld#31]
When using JB4JSON-LD in a Spring Boot-based application, there is problem with classpath scanning. It expects multi-release info in `META-INF` while it can be in `BOOT-INF` for Spring Boot applications.

**Comment by psiotwo** [comment]
Hypothesis: loading of WAR files never worked, because in WAR files the classes are bundled under WEB-INF/classes and not in the jar root.

(see https://github.com/kbss-cvut/jb4jsonld/blob/092f1a04fc783431a4a3f23f319252814c699475/src/main/java/cz/cvut/kbss/jsonld/deserialization/util/ClasspathScanner.java#L117)

**Comment by psiotwo** [comment]
fixed via #32
